# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ecc05c08e0771b6cb28e05a3456102b32ffded1837771ce55499e57531fe8e397a6e219d96d3afedc455aa39e5f7e6359b94ef49cf6b03242603f9f331b0341

test:
  secret_key_base: 06c1016f78f4daf768d066f97456976de6fa94f4e5b9f8dc28c0242d8cace173f3c06eebb0c5519db411b188fb17c71aa01d88b0524d976dcb15ed6e06e1d408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
